# Generated by Django 2.1.5 on 2019-01-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='available',
        ),
        migrations.AddField(
            model_name='icecream',
            name='availability',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('seasonal', 'Seasonal')], default='Cookies and Creme', max_length=100),
        ),
    ]
