# Generated by Django 2.1.5 on 2019-01-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20190125_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='availability',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Seasonal', 'Seasonal')], default='Cookies and Creme', max_length=100),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='base',
            field=models.CharField(choices=[('Chocolate', 'Chocolate'), ('Vanilla', 'Vanilla')], default='Vanilla', max_length=100),
        ),
    ]
